/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcguifinal;

import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnCRUDEspecies = new javax.swing.JButton();
        btnCRUDClientes = new javax.swing.JButton();
        btnCRUDProductos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnHistorialVentas1 = new javax.swing.JToggleButton();
        btnHistorialVentas = new javax.swing.JToggleButton();
        btnHistorialVentas2 = new javax.swing.JToggleButton();
        btnHistorialVentas3 = new javax.swing.JToggleButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("         MENU VITALPET");

        btnCRUDEspecies.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDEspecies.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        btnCRUDEspecies.setText("ESPECIES");
        btnCRUDEspecies.addActionListener(this::btnCRUDEspeciesActionPerformed);

        btnCRUDClientes.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDClientes.setText("𝓒𝓛𝓘𝓔𝓝𝓣𝓔");
        btnCRUDClientes.addActionListener(this::btnCRUDClientesActionPerformed);

        btnCRUDProductos.setBackground(new java.awt.Color(0, 204, 204));
        btnCRUDProductos.setText("𝓟𝓡𝓞𝓓𝓤𝓒𝓣𝓞𝓢");
        btnCRUDProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCRUDProductos.addActionListener(this::btnCRUDProductosActionPerformed);

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnHistorialVentas1.setBackground(new java.awt.Color(0, 255, 255));
        btnHistorialVentas1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnHistorialVentas1.setText("MASCOTAS");
        btnHistorialVentas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialVentas1MouseClicked(evt);
            }
        });
        btnHistorialVentas1.addActionListener(this::btnHistorialVentas1ActionPerformed);

        btnHistorialVentas.setBackground(new java.awt.Color(0, 255, 255));
        btnHistorialVentas.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnHistorialVentas.setText("HISTORIAL DE VENTAS");
        btnHistorialVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialVentasMouseClicked(evt);
            }
        });
        btnHistorialVentas.addActionListener(this::btnHistorialVentasActionPerformed);

        btnHistorialVentas2.setBackground(new java.awt.Color(0, 255, 255));
        btnHistorialVentas2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnHistorialVentas2.setText("Detalle Ventas");
        btnHistorialVentas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialVentas2MouseClicked(evt);
            }
        });
        btnHistorialVentas2.addActionListener(this::btnHistorialVentas2ActionPerformed);

        btnHistorialVentas3.setBackground(new java.awt.Color(0, 255, 255));
        btnHistorialVentas3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnHistorialVentas3.setText("Ventas");
        btnHistorialVentas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialVentas3MouseClicked(evt);
            }
        });
        btnHistorialVentas3.addActionListener(this::btnHistorialVentas3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCRUDClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnHistorialVentas))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnHistorialVentas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(60, 60, 60)
                                    .addComponent(btnHistorialVentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCRUDEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHistorialVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(btnCRUDProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCRUDClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCRUDProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHistorialVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCRUDEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistorialVentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistorialVentas3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnHistorialVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Fin de ejecucion :)");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCRUDClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gestion de Clientes ");
        menu_clientes ingresar = new menu_clientes();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDClientesActionPerformed

    private void btnCRUDProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDProductosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gestion de Productos ");
        menu_productos ingresar = new menu_productos();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDProductosActionPerformed

    private void btnCRUDEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDEspeciesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Especies de Mascotas ");
        menu_especies ingresar = new menu_especies();
        ingresar.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnCRUDEspeciesActionPerformed

    private void btnHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Historial de Ventas ");
        historialventas ingresar = new historialventas();
        ingresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialVentasActionPerformed

    private void btnHistorialVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialVentasMouseClicked

    private void btnHistorialVentas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentas1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialVentas1MouseClicked

    private void btnHistorialVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentas1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, " Mascotas ");
        menu_mascotas ingresar = new menu_mascotas();
        ingresar.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnHistorialVentas1ActionPerformed

    private void btnHistorialVentas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentas2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialVentas2MouseClicked

    private void btnHistorialVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentas2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Detalle Ventas ");
        menu_detalle_ventas ingresar = new menu_detalle_ventas();
        ingresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistorialVentas2ActionPerformed

    private void btnHistorialVentas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentas3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialVentas3MouseClicked

    private void btnHistorialVentas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialVentas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialVentas3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDClientes;
    private javax.swing.JButton btnCRUDEspecies;
    private javax.swing.JButton btnCRUDProductos;
    public javax.swing.JToggleButton btnHistorialVentas;
    public javax.swing.JToggleButton btnHistorialVentas1;
    public javax.swing.JToggleButton btnHistorialVentas2;
    public javax.swing.JToggleButton btnHistorialVentas3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
